<a href="https://colab.research.google.com/github/JonathanAMP/StaTistics/blob/main/Jonathan_Mendez_Ponce_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import imageio
from PIL import Image
#importing these lines to be able to plot, graphs and other images.

### Loops

In [6]:
for i in range(100):
    print(i)
    # Making a For loop with a range of 100 to be able to produce numbers 1-100 in a repeated sequence.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [7]:
for i in range(5,8):
    print(i)
    #Creating a For loop that has the range of 5-8 making it able to print the numbers in between 5 and 8.

5
6
7


In [8]:
for i in range(3):
    print( "Test Number: " , i )
    # Creating a For loop that is able to print 'Test Number:' with the range of 3, starting from 0 and ending in 2, repeatedly.

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [9]:
def square(x):
    return x**2
    #Creating a function that is able to multiply any number by the power of 2.

In [10]:
square(5)
#Testing the fucntion to see if it is able correctly multiply the number by the power of two.

25

In [11]:
square(square(2))
#Testing if we can put two functions inside each other and get the corect calculations.

16

In [12]:
square(square(square(2)))
#Testing if we can put three functions inside each other and get the corect calculations.


256

In [13]:
square(123456)
#Testing the fucntion to see if it is able correctly multiply the number by the power of two.

15241383936

In [14]:
square(square(5))
#Testing if we can put two functions inside each other and get the corect calculations.

625

In [15]:
def add_two(x):
    return x+2
    #Creating a function that is able to add any number by two.

In [16]:
add_two(5)
#Testing the function to see if it is able to correctly calculate different numbers.

7

In [17]:
square(add_two(5))
#Testing if you can insert two different functions and get the correct calculations.

49

### Logical Branching

In [18]:
choice = "apple"
#Initializing a string.

In [19]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")
    #Using a if-else statement to see if the option chosen is either apples or not apples.

You choose apples.


In [20]:
choice = "orange"
#Initializing a string with the same variable but with 'orange'.

In [21]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")
    #Testing to see if the if-else statement would change since the varible would be false.

You did not choose apples.


In [22]:
choice = "apple"
#Initializing the same string back in to 'apple'.

In [23]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")
    #Adding more to the if-else statement for either option to print more words like 'Thank you, shop again!'.

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [24]:
choice = input("Please enter your choice (i.e. apple): ")
#Inizializing a variable that is able to be chosen by the user running the code.

Please enter your choice (i.e. apple): apple


In [25]:
choice
#Testing if the string actually recieved the information.

'apple'

In [26]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")
    #Testing the if-else statement to see if it will work since the user is able to type anything 
    #so if the user's choice becomes a 'passionfruit' then the code will print 'you did not choose apples or oranges'

You choose apples.


#### Coins

In [44]:
np.random.random()
#Makes a random number between 0 and 1

0.7294077957326145

In [45]:
np.random.random() > 0.5
#Its says true if the random number is greater than 0.5 and will say false if the random number is less than 0.5.

False

In [46]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")
        #Creating a function in where the code will print 'heads' or 'tails' depending whether the number is greater or less than 0.5.

In [47]:
flip_coin()
#Testing the function to see if it works.

Tails


### Graphics Output

In [48]:
from IPython.core.display import display, HTML
#A code that is able to display words in fonts.

In [49]:
display(HTML('<h1>Hello, world!</h1>'))
#Creating a display in where the user wants to show 'Hello, world!' in bold.

In [50]:
def coin():
  return np.random.randint(2)
  #Creating a random number within a range, fro example the range is 2 
  #meaning that that the only two numbers that are going ot be displayed randomly is 0 and 1 

In [51]:
coin()
#Testing the function is working.

0

In [52]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))
#Making the code display a jpg from the internet 

In [53]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'
#Initializing a varible to hold the pictures from the internet.

In [54]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))
  #Creating a function that is able to display the jpg.

In [55]:
show_img(heads)
#Testing the fuction.

In [56]:
show_img(tails)
#Testing the function.

In [57]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)
        #Creating a fucntion that is able to show the jpg to replicate flipping a coin.

In [58]:
flip_coin()
#Testing the function.

In [59]:
for i in range(5):
    flip_coin()
    #A loop that flips the coin 5 times.

In [60]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)
  #Coin flip function.

### Cards

In [61]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x
    #Creating a function where it is able to shuffle an array of numbers.

In [62]:
a = np.arange(52)
#Giveing 'a' the array of 52 numbers.

In [63]:
shuffle(a)
#Randomly shuffles the numbers of the array.

array([12, 39,  9, 46, 45, 43, 41, 23, 37,  0,  2, 44,  1, 19,  5, 24, 48,
       21, 42, 10, 26, 18, 27, 28, 30, 22, 47, 31, 20, 33, 35, 29, 40, 25,
       14, 16,  6, 34,  8, 38, 13, 11, 32,  3, 50, 17,  7, 15, 36, 49, 51,
        4])

In [103]:
np.random.permutation(52)
#Randomly shuffes the numbers of the array.


array([20, 24, 39,  3, 27, 48,  2, 18, 41, 19,  0, 22, 10, 30, 42, 25, 13,
       17,  1,  8, 23, 51, 45, 44, 21, 40, 33,  7, 34, 38, 43, 47, 37, 35,
        6, 28,  5, 36, 31, 16,  4,  9, 14, 50, 26, 29, 46, 12, 11, 49, 15,
       32])

### Speed Test

In [65]:
%%timeit
shuffle(a)


176 µs ± 3.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [66]:
%%timeit
np.random.permutation(52)

3.4 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [67]:
import numpy as np
#Importing to make sure code executes.

In [68]:
np.random.permutation(52)
#Shuffling the numbers of the array.

array([ 8,  5, 14, 29, 45, 16, 40, 17, 13, 32, 11, 35, 30, 37, 12, 49, 15,
       27, 46,  7, 25,  0, 26, 38, 21, 36, 24, 43, 34, 31, 18, 47,  6,  1,
        4, 51, 44, 48, 22, 50,  3, 41, 20, 23, 33, 42,  9, 19, 39,  2, 10,
       28])

In [69]:
cards = np.random.permutation(52)
#Initializing a variable to be able to shuffle the array's numbers.

In [70]:
cards
#Testing to see what the variable holds.

array([18,  9, 10, 39,  2, 35, 46,  6, 44, 12, 33, 14, 20, 16, 37,  7,  8,
       21, 11, 36, 47,  1, 51, 28, 45,  3, 40, 24, 42, 41, 30, 27, 25, 29,
       31, 15, 13, 34,  4, 43, 49, 23, 22, 50, 26, 38, 19,  5, 48, 17, 32,
        0])

In [71]:
cards[0]
#Seeing the number array[0] holds.

18

In [72]:
cards[1]
#Seeing the number array[1] holds.

9

In [73]:
cards[2]
#Seeing the number array[2] holds.

10

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [74]:
np.arange(52).reshape(4,13)
#Reshaping the array into 4 rows and 13 columns.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [75]:
np.arange(52).reshape(4,13)%13
#Reshaping the array into 4 rows and 13 columns and dividing them by 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [76]:
np.arange(52).reshape(4,13)//13
#Reshaping the array into 4 rows and 13 columns and dividing them by 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [77]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']
#Inizializing strings.

In [78]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]
    #Creating a fucntion that is able to find the suit and name of a card.

In [79]:
card_name(0)
#Testing the functions.

'Ace of Clubs'

In [80]:
card_name(51)
#Testing the functions.

'King of Diamonds'

In [81]:
cards = np.random.permutation(52)
#Initializing a variable to be able to shuffle the array's numbers.

In [82]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])
#Initializing variable to see numbers are on the top, second or last card of the deck.

In [83]:
top_of_deck, second_card_in_deck, last_card_in_deck
#Testing the variables.

('Six of Clubs', 'Queen of Hearts', 'Five of Hearts')

In [84]:
for i in range(5):
    print(card_name(cards[i]))
    #Creating a for loop that runs 5 times where it prints the name and suit of random cards.

Six of Clubs
Queen of Hearts
Ace of Clubs
Three of Spades
Four of Clubs


In [85]:
for i in range(15):
    print(card_name(cards[i]))
    #Creating a for loop that runs 15 times where it prints the name and suit of random cards.

Six of Clubs
Queen of Hearts
Ace of Clubs
Three of Spades
Four of Clubs
Five of Spades
King of Spades
Jack of Clubs
King of Hearts
Queen of Clubs
Five of Diamonds
Nine of Diamonds
Two of Hearts
Three of Hearts
Six of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [86]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"
#Giving varibales a jpg from the internet.

In [87]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']
#Creating characters for suit and card.

In [88]:
i = np.random.randint(4)
j = np.random.randint(13)
#Giving them random numbers.

In [89]:
i,j
#Creating a coordinate.

(3, 0)

In [90]:
suit[i]
#Testing out the variable.

'l'

In [91]:
card[j]
#Testing out the variable.

'a'

In [92]:
from IPython.core.display import display, HTML
#Importing to be able to insert an image of the internet.

In [93]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))
  #Function used to display the jpg.

In [94]:
img = card_url_head + suit[i] + card[j] + card_url_tail
#Adding everything to a singular variable.

In [95]:
show_img(img)
#Testing to see if it will show an image from the jpg.

In [96]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]
    #Creating a fucntion to return the image of cards.

In [97]:
card_image(3) 
#Testing variable.

'k4'

In [98]:
img = card_url_head + card_image(3) + card_url_tail
#Adding the images to the variable.

In [99]:
show_img(img)
#Testing the function.

In [100]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)
    #Creating a loop that runs 52 times to show the image of each value of card.